### ISSUE TITLE
Validate locked normals

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-magenta#15]
### Goal

A modeling validator looking for whether a mesh has locked normals, something that can cause trouble during rendering but primarily an annoyance for rigging/animation where the mesh appears dark in places that would logically be bright, and vice versa.

**Comment by BigRoy** [comment]
Tested implementation from BigRoy@d8966a981e10c37cfb525b0319a7bbef841386df some more and seems to be working great!

**Comment by mottosso** [comment]
Awesome sauce. :) I'll join you on Magenta today after me old breakfast.

**Comment by BigRoy** [comment]
This seems to be in the master branch now and functioning correctly for the models. Shall we close this, or do you think it's better to keep it open for some more discussion?

**Comment by mottosso** [comment]
Sounds complete, so let's close. Conversation can still go on if there's anything related to it that needs to be said.
