### ISSUE TITLE
Alembic Wrapper extractor doesn't include motion

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-magenta#33]
For some reason, moving meshes doesn't come along when wrapping it in a Maya scene.
- [`wrap_alembic.py`](https://github.com/pyblish/pyblish-magenta/blob/65534cd0d5796d8619ba56ae829973883023fa83/pyblish_magenta/plugins/wrap_alembic.py)

**Comment by mottosso** [comment]
Ok, found the issue.

```
# Error: Cannot read file c:/users/marcus/appdata/local/temp/tmpoeq1vw/ben01_pc.abc # 
```

The alembic wrapper is importing before integration, thus referencing the temporary alembic file. This is reason enough to move the plug-in post-integration.

**Comment by mottosso** [comment]
And the reason I was getting anything at all, was because of how Maya permanently imports the alembic when a mesh has no motion, storing the data in the file directly. Really don't like this, can't see a reason why it couldn't simply reference the alembic even in cases of no motion.. Basically an optimisation gone wrong.

**Comment by BigRoy** [comment]
> Ok, found the issue.

Good spot. Seems like we'll be fixing this!

> And the reason I was getting anything at all, was because of how Maya permanently imports the alembic when a mesh has no motion, storing the data in the file directly. Really don't like this, can't see a reason why it couldn't simply reference the alembic even in cases of no motion.. Basically an optimisation gone wrong.

Yes, it's weird that it does that. Haven't found an option to keep those connected as well as of yet.

**Comment by mottosso** [comment]
It must be something built into the script that imports the alembic and connects things up. It must be removing history if there's no motion. Maybe we can find a way to fix that.
