### ISSUE TITLE
Validate non-zero vertices

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-magenta#34]
Vertices can have positions that messes with subsequent deformers and are difficult to track down.

Make sure vertices are zeroed out.

**Comment by BigRoy** [comment]
Can you elaborate on this? What do you mean exactly?

**Comment by mottosso** [comment]
Have a look at Ben's model and compare v010 to v012.

In v010, some vertices have values on their positions in the Channel Box. It means that if you connect another mesh into that shape's `inMesh`, those values will get added on-top. Which means both the source and target must both have these values, which is very unlikely, as they only follow along when you duplicate, not when you, for example, add a deformer and get the added intermediate shape.

**Comment by BigRoy** [comment]
This should be fixed since #35
