### ISSUE TITLE
Shaders included in model export

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-magenta#41]
They shouldn't be, right?

**Comment by BigRoy** [comment]
Try importing the models generated with your fix. You'll see they are imported as only a wireframe model. Upon import they don't even receive the `lambert1` (default) shading.

The custom extractor we used before would fix that.

**Comment by mottosso** [comment]
I'm a little reluctant to include that because it was so big. Do you think we could implement that here for this specific case?

**Comment by BigRoy** [comment]
Yes, it's only the `shader` part from that extractor of course. Basically temporarily assigning the `defaultShadingEngine` for the duration of the export context.

You'd still export with `shaders=True` then.
